// =============================================================
// Webhook Service
// =============================================================
// Per-project webhook settings and YAML generation.
// =============================================================

import { randomBytes } from "crypto";
import { Project } from "../../models/Project.js";
import { User } from "../../models/User.js";
import { ProjectShare } from "../../models/ProjectShare.js";

// ─── Helper: Create domain error ───────────────────────────

function domainError(msg, code, status = 400) {
  const e = new Error(msg);
  e.code = code;
  e.status = status;
  return e;
}

// ─── Helper: Assert ownership ─────────────────────────────

async function assertOwnership(projectId, userId) {
  const project = await Project.findOne({ _id: projectId, userId });
  if (!project)
    throw domainError("Project not found.", "PROJECT_NOT_FOUND", 404);
  return project;
}

// ─── Generate GitHub Actions Workflow YAML ────────────────
// Generates a per-project workflow that:
//   1. Uses the project's specific webhook secret from GitHub Actions secrets
//   2. Sends to the per-project endpoint: /api/webhook/:projectId
//   3. Writes payload to a temp file using Python (no heredoc byte issues)
//   4. Signs with openssl dgst -sha256 -hmac
//   5. Sends with curl --data-binary @file

export function generateWorkflowYAML({ apiBaseUrl, projectId, repoName }) {
  const base = (apiBaseUrl || "https://your-docnine-instance.com").replace(
    /\/$/,
    "",
  );

  return `# .github/workflows/docnine.yml
# Auto-generated by Docnine
# Triggers an incremental documentation sync on every push to main.
#
# SETUP:
#   1. Go to your repo Settings → Secrets and variables → Actions
#   2. Add a secret named DOCNINE_WEBHOOK_SECRET with the value from:
#      https://app.docnine.ai/projects/${projectId}/webhook
#   3. Commit this file to your repository
#
# The workflow will automatically trigger on push and send a webhook
# to Docnine with the code changes. Only changed files are re-documented.

name: Docnine Auto-Document

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.jsx'
      - '**.py'
      - '**.go'
      - '**.rs'
      - '**.java'
      - '**.kt'
      - '**.prisma'
      - '**.graphql'
      - '**.sql'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - 'requirements.txt'
      - 'go.mod'
      - 'Cargo.toml'
      - 'pom.xml'
      - 'composer.json'
  workflow_dispatch:

jobs:
  docnine-sync:
    name: Docnine Sync
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Trigger Docnine Webhook
        env:
          WEBHOOK_SECRET: \${{ secrets.DOCNINE_WEBHOOK_SECRET }}
          PROJECT_ID: ${projectId}
        run: |
          # Build the push payload that mimics GitHub's format
          PAYLOAD=\$(python3 << 'PYTHON_EOF'
import json
import os
import sys

payload = {
    "ref": "\${{ github.ref }}",
    "after": "\${{ github.sha }}",
    "pusher": {
        "name": "\${{ github.actor }}"
    },
    "repository": {
        "html_url": "\${{ github.server_url }}/\${{ github.repository }}",
        "full_name": "\${{ github.repository }}",
        "default_branch": "\${{ github.event.repository.default_branch || 'main' }}"
    },
    "commits": \${{ toJson(github.event.commits) }}
}

print(json.dumps(payload, separators=(',', ':')))
PYTHON_EOF
          )

          # Write payload to a temp file (byte-perfect, no processing)
          echo -n "\${PAYLOAD}" > /tmp/webhook_payload.json

          # Compute HMAC-SHA256 signature
          SIGNATURE="sha256=\$(openssl dgst -sha256 -hmac "\${WEBHOOK_SECRET}" /tmp/webhook_payload.json | awk '{print \$2}')"

          echo "Sending webhook to ${base}/api/webhook/\${PROJECT_ID}"

          # Send with curl --data-binary for byte-perfect delivery
          HTTP_STATUS=\$(curl -s -o /tmp/webhook_response.json -w "%{http_code}" \\
            -X POST \\
            -H "Content-Type: application/json" \\
            -H "X-Hub-Signature-256: \${SIGNATURE}" \\
            -H "X-GitHub-Event: push" \\
            --data-binary @/tmp/webhook_payload.json \\
            "${base}/api/webhook/\${PROJECT_ID}")

          RESPONSE=\$(cat /tmp/webhook_response.json)
          echo "HTTP Status: \${HTTP_STATUS}"
          echo "Response: \${RESPONSE}"

          # Fail the step if the server returned an error
          if [ "\${HTTP_STATUS}" -ge 400 ]; then
            echo "❌ Webhook returned HTTP \${HTTP_STATUS}"
            echo "Error: \$(echo "\${RESPONSE}" | jq -r '.error // .message // "Unknown error"')"
            exit 1
          fi

          echo "✓ Webhook delivered successfully"
`;
}

// ────────────────────────────────────────────────────────────
// PUBLIC FUNCTIONS
// ────────────────────────────────────────────────────────────

/**
 * Get webhook settings for a project.
 * Owner-only. Returns the secret only via this endpoint.
 *
 * @param {{ projectId, userId, apiBaseUrl }}
 * @returns {{ webhookUrl, secret, yaml, lastWebhookAt, lastWebhookStatus, webhookEnabled }}
 */
export async function getWebhookSettings({ projectId, userId, apiBaseUrl }) {
  const project = await assertOwnership(projectId, userId);

  const webhookUrl = `${(apiBaseUrl || "").replace(/\/$/, "")}/api/webhook/${projectId}`;
  const yaml = generateWorkflowYAML({
    apiBaseUrl,
    projectId: projectId,
    repoName: project.repoName,
  });

  return {
    projectId: projectId,
    webhookUrl,
    secret: project.webhookSecret,
    yaml,
    lastWebhookAt: project.lastWebhookAt || null,
    lastWebhookStatus: project.lastWebhookStatus || null,
    webhookEnabled: project.webhookEnabled,
    createdAt: project.createdAt,
  };
}

/**
 * Rotate the webhook secret (regenerate it).
 * Owner-only. Returns the new secret and updated YAML.
 *
 * @param {{ projectId, userId, apiBaseUrl }}
 * @returns {{ webhookUrl, secret, yaml }}
 */
export async function rotateWebhookSecret({ projectId, userId, apiBaseUrl }) {
  const project = await assertOwnership(projectId, userId);

  // Generate new 32-byte hex secret
  const newSecret = randomBytes(32).toString("hex");

  // Update the project
  project.webhookSecret = newSecret;
  await project.save();

  const webhookUrl = `${(apiBaseUrl || "").replace(/\/$/, "")}/api/webhook/${projectId}`;
  const yaml = generateWorkflowYAML({
    apiBaseUrl,
    projectId: projectId,
    repoName: project.repoName,
  });

  return {
    projectId: projectId,
    webhookUrl,
    secret: newSecret,
    yaml,
    message:
      "Secret rotated. Update your GitHub secret to continue using webhooks.",
  };
}

/**
 * Update webhook enabled/disabled status.
 * Owner-only.
 *
 * @param {{ projectId, userId, webhookEnabled }}
 * @returns {{ webhookEnabled }}
 */
export async function updateWebhookSettings({
  projectId,
  userId,
  webhookEnabled,
}) {
  const project = await assertOwnership(projectId, userId);

  if (typeof webhookEnabled !== "boolean") {
    throw domainError(
      "webhookEnabled must be a boolean",
      "INVALID_PARAMETER",
      400,
    );
  }

  project.webhookEnabled = webhookEnabled;
  await project.save();

  return {
    projectId: projectId,
    webhookEnabled: project.webhookEnabled,
  };
}

/**
 * Internal: Update webhook delivery status after a push event.
 * Called from the per-project webhook handler.
 * Non-critical — swallow errors.
 *
 * @param {{ projectId, status: "success" | "failed" | "skipped" }}
 */
export async function updateWebhookStatus({ projectId, status }) {
  try {
    await Project.findByIdAndUpdate(projectId, {
      $set: {
        lastWebhookAt: new Date(),
        lastWebhookStatus: status,
      },
    });
  } catch (err) {
    // Non-critical update — log but don't throw
    console.error(
      `[webhook] Failed to update status for project ${projectId}:`,
      err.message,
    );
  }
}
